import Head from "next/head";
import { Container, VStack, Box } from "@chakra-ui/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>andresin87</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container minW="100vw" height="100vh" padding={0}>
        <VStack spacing={0} align="stretch" alignContent="stretch" minH="100vh">
          <Box h="40px" bg="yellow.200">
            <Container
              maxW={{
                sm: "container.sm",
                md: "container.md",
                lg: "container.lg",
                xl: "container.xl",
              }}
            >
              header
            </Container>
          </Box>
          <Box p={0} flexGrow="1" bg={"blackAlpha.300"}>
            <Container
              maxH="40px"
              maxW={{
                sm: "container.sm",
                md: "container.md",
                lg: "container.lg",
                xl: "container.xl",
              }}
            >
              Container
            </Container>
          </Box>

          <Box h="40px" bg="pink.100">
            <Container
              maxW={{
                sm: "container.sm",
                md: "container.md",
                lg: "container.lg",
                xl: "container.xl",
              }}
            >
              Footer
            </Container>
          </Box>
        </VStack>
      </Container>
    </div>
  );
}
